app/src/main/java/es/jvbabi/vplanplus/data/repository/VPlanRepositoryImpl.kt

- show full stack trace
- fixed missing leading zero from 1. to 9. day of the month
Refer to #8 as the issue

Show errors on sync problems

---

build.gradle.kts

- updated gradle

---

app/src/main/java/es/jvbabi/vplanplus/ui/screens/home/HomeScreen.kt
app/src/main/java/es/jvbabi/vplanplus/ui/screens/home/Menu.kt

- open settings on long click

---

app/src/main/java/es/jvbabi/vplanplus/ui/screens/home/HomeScreen.kt
app/src/main/java/es/jvbabi/vplanplus/ui/screens/home/components/placeholders/Holiday.kt
app/src/main/java/es/jvbabi/vplanplus/ui/screens/home/components/placeholders/NoData.kt
app/src/main/java/es/jvbabi/vplanplus/ui/screens/home/components/placeholders/Weekend.kt
app/src/main/res/values-de/strings.xml
app/src/main/res/values/strings.xml

44 missing placeholder screens when there wont be data for the day

---

app/src/main/java/es/jvbabi/vplanplus/ui/screens/settings/SettingsScreen.kt

- large app bar in settings

---

app/src/main/java/es/jvbabi/vplanplus/data/repository/BaseDataRepositoryImpl.kt

- return better response

---

app/src/main/java/es/jvbabi/vplanplus/ui/common/SubjectIcon.kt

- optimized some icons

---

app/src/main/AndroidManifest.xml
app/src/main/java/es/jvbabi/vplanplus/MainActivity.kt
app/src/main/java/es/jvbabi/vplanplus/ui/Navigation.kt
app/src/main/java/es/jvbabi/vplanplus/worker/SyncWorker.kt

- fixed notification onclick

---

app/build.gradle.kts
app/src/main/java/es/jvbabi/vplanplus/ui/preview/Lessons.kt
app/src/main/java/es/jvbabi/vplanplus/ui/screens/home/HomeScreen.kt
app/src/main/java/es/jvbabi/vplanplus/ui/screens/home/components/LessonCard.kt
app/src/main/res/values-de/strings.xml
app/src/main/res/values/strings.xml

45 suggest find unoccupied room when a lesson does not take place in the middle of the day

---

app/src/main/java/es/jvbabi/vplanplus/ui/common/Layout.kt
app/src/main/java/es/jvbabi/vplanplus/ui/screens/home/HomeScreen.kt
app/src/main/java/es/jvbabi/vplanplus/ui/screens/home/components/LessonCard.kt
app/src/main/java/es/jvbabi/vplanplus/ui/screens/home/components/ViewSwitcher.kt

Ref #72
Fixed by removing currentlessoncard and adding progressbar into every lessoncard

72 current lesson not respecting week layout

---

app/src/main/java/es/jvbabi/vplanplus/worker/SyncWorker.kt

 - don't sync if there aren't any profiles

---

app/src/main/java/es/jvbabi/vplanplus/data/source/online/OnlineRequest.kt

- changed userAgent to VPlanPlus

---

app/build.gradle.kts
app/src/main/java/es/jvbabi/vplanplus/data/repository/VPlanRepositoryImpl.kt
app/src/main/java/es/jvbabi/vplanplus/data/source/online/OnlineRequest.kt
app/src/main/java/es/jvbabi/vplanplus/domain/usecase/onboarding/DefaultLessonUseCase.kt

- fixed one digit month request bug

- fixed default lesson loading during holidays

---

app/src/main/java/es/jvbabi/vplanplus/domain/usecase/VPlanUseCases.kt

- fixed room splitting via fancy algorithm

---

app/src/main/java/es/jvbabi/vplanplus/ui/screens/home/search/room/RoomSearch.kt

- hide filter options when last lesson is over

- fixed wrong indicator

---

app/build.gradle.kts
app/src/main/java/es/jvbabi/vplanplus/ui/screens/home/HomeScreen.kt
app/src/main/java/es/jvbabi/vplanplus/ui/screens/home/components/home/Content.kt
app/src/main/java/es/jvbabi/vplanplus/ui/screens/home/viewmodel/HomeViewModel.kt

- update ui after sync

---

app/src/main/java/es/jvbabi/vplanplus/feature/onboarding/ui/F_OnboardingDefaultLessonScreen.kt
app/src/main/java/es/jvbabi/vplanplus/feature/onboarding/ui/OnboardingViewModel.kt
app/src/main/res/values-de/strings.xml
app/src/main/res/values/strings.xml

will need to add a notification for when the data actually exists and the user has the option to resolve the issue

Fix for #262

---

app/src/main/java/es/jvbabi/vplanplus/feature/main_grades/ui/calculator/GradeCalculatorScreen.kt
app/src/main/java/es/jvbabi/vplanplus/feature/main_grades/ui/components/Average.kt

- crash fix

---

app/src/main/java/es/jvbabi/vplanplus/data/model/DbVppId.kt
app/src/main/java/es/jvbabi/vplanplus/data/model/combined/CVppId.kt
app/src/main/java/es/jvbabi/vplanplus/data/repository/RoomRepositoryImpl.kt
app/src/main/java/es/jvbabi/vplanplus/data/repository/VppIdRepositoryImpl.kt
app/src/main/java/es/jvbabi/vplanplus/data/source/database/VppDatabase.kt
app/src/main/java/es/jvbabi/vplanplus/data/source/database/dao/VppIdDao.kt
app/src/main/java/es/jvbabi/vplanplus/domain/model/VppId.kt
app/src/main/java/es/jvbabi/vplanplus/domain/repository/VppIdRepository.kt
app/src/main/java/es/jvbabi/vplanplus/domain/usecase/find_room/BookRoomUseCase.kt
app/src/main/java/es/jvbabi/vplanplus/domain/usecase/find_room/CanBookRoomUseCase.kt
app/src/main/java/es/jvbabi/vplanplus/domain/usecase/vpp_id/GetVppIdDetailsUseCase.kt
app/src/main/java/es/jvbabi/vplanplus/feature/main_homework/shared/data/repository/HomeworkRepositoryImpl.kt

475 task automatically refresh vppid cache

---

app/src/main/java/es/jvbabi/vplanplus/feature/main_home/feature_search/ui/components/Menu.kt
app/src/main/java/es/jvbabi/vplanplus/feature/main_home/feature_search/ui/components/ProfileIcon.kt

- adaptive font size depending on name

---

app/src/main/java/es/jvbabi/vplanplus/feature/onboarding/stages/e_profile/domain/usecase/GetProfileOptionsUseCase.kt

#605 Sorting

---

app/build.gradle.kts
app/src/main/java/es/jvbabi/vplanplus/feature/main_homework/list/domain/usecase/ToggleDoneStateUseCase.kt
app/src/main/java/es/jvbabi/vplanplus/feature/main_homework/list/ui/HomeworkListScreen.kt
app/src/main/java/es/jvbabi/vplanplus/feature/main_homework/list/ui/HomeworkListViewModel.kt
app/src/main/java/es/jvbabi/vplanplus/feature/main_homework/list/ui/components/HomeworkItem.kt
app/src/main/java/es/jvbabi/vplanplus/feature/main_homework/shared/domain/usecase/UpdateHomeworkUseCase.kt
app/src/main/res/values/strings.xml

- Fix für #642 (Hausaufgabenstatus wird nicht korrekt gesynced)

VPP_20240820-android-1

---

app/build.gradle.kts
app/src/main/java/es/jvbabi/vplanplus/domain/model/xml/VPlanData.kt
app/src/main/java/es/jvbabi/vplanplus/domain/usecase/sync/DoSyncUseCase.kt

- https://github.com/VPlanPlus-Project/VPlanPlus/issues/661

VPP_20240928-android1

---

app/build.gradle.kts
app/src/main/java/es/jvbabi/vplanplus/feature/main_grades/view/domain/model/Grade.kt
app/src/main/java/es/jvbabi/vplanplus/feature/main_grades/view/domain/model/Interval.kt
app/src/main/java/es/jvbabi/vplanplus/feature/main_grades/view/ui/view/GradesViewModel.kt

VPP_20240929-android1
